[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
ffi = true
fs_permissions = [{ access = "read", path = "./" }]
evm_version = "cancun"

[fuzz]
runs = 1000
max_test_rejects = 65536

[invariant]
runs = 256
depth = 50

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
